# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array 
list_1 = [50, 60, 80, 100, 200, 300, 500, 600]
list_1

[50, 60, 80, 100, 200, 300, 500, 600]

In [2]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [3]:
type(my_numpy_array)

numpy.ndarray

In [4]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[2, 5, 8], [7, 3, 6]  ])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [5]:
matrix = np.array([[3, 7, 9, 3], [4, 3, 2, 2] ])
matrix

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [6]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

array([0.74730311, 0.92243701, 0.93298068, 0.13230509, 0.51877759,
       0.43948794, 0.66252066, 0.41357854, 0.34135613, 0.09062186,
       0.38605103, 0.76114045, 0.54784301, 0.69345713, 0.42262542,
       0.67881936, 0.10337873, 0.96384444, 0.39023453, 0.78593135])

In [7]:
# you can create a matrix of random number as well
x = np.random.rand(3, 3)
x

array([[0.04387993, 0.96647767, 0.54003224],
       [0.55425968, 0.87766102, 0.34281494],
       [0.9074687 , 0.58988337, 0.91658611]])

In [8]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 50)
x

38

In [9]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)
x

array([ 8, 91, 31, 56,  9, 40,  5, 80, 12, 35, 27, 22, 11, 82, 51])

In [10]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Matrix of ones
x = np.ones((7, 7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# Array of zeros
x = np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [14]:
x = int(input('please enter a positive integer value: '))
y = np.random.randint(0, x, 10)
y

please enter a positive integer value: 40


array([35,  4, 14, 27, 25, 19, 35, 32, 27,  1])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [15]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Add 2 numpy arrays together
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [19]:
sqr_root = np.sqrt(squared)
sqr_root

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [21]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])

Z = np.sqrt(X**2 + Y**2)
Z

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [22]:
my_numpy_array = np.array([3, 5, 6, 2, 8, 10, 20, 50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [23]:
# Access specific index from the numpy array
my_numpy_array[-1]

50

In [24]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_array[0:3]

array([3, 5, 6])

In [25]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[0:4] = 7
my_numpy_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [26]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1, 10, (4, 4))
matrix

array([[5, 7, 7, 2],
       [6, 2, 8, 7],
       [4, 7, 2, 5],
       [9, 6, 5, 1]])

In [27]:
# Get a row from a mtrix
matrix[0:3]

array([[5, 7, 7, 2],
       [6, 2, 8, 7],
       [4, 7, 2, 5]])

In [28]:
# Get one element
matrix[0][0]

5

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [29]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X[-1] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [30]:
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[3, 9, 3, 4, 5],
       [7, 2, 5, 7, 6],
       [1, 5, 2, 5, 1],
       [3, 6, 3, 2, 1],
       [8, 3, 8, 4, 2]])

In [31]:
new_matrix = matrix[ matrix < 6 ]
new_matrix

array([3, 3, 4, 5, 2, 5, 1, 5, 2, 5, 1, 3, 3, 2, 1, 3, 4, 2])

In [32]:
# Obtain odd elements only
odd_matrix = matrix[ matrix % 2 != 0 ]
odd_matrix

array([3, 9, 3, 5, 7, 5, 7, 1, 5, 5, 1, 3, 3, 1, 3])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [33]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[ X < 0] = 0
X[ X % 2 ==1 ] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [34]:
# Pandas is a atad manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [4]:
import pandas as pd

In [36]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444],
                               'Bank Client Name': ['Chanel', 'Steve', 'Mitch', 'Ryan'],
                                'Net Worth [$]': [3500, 29000, 10000, 2000],
                                 'Years with bank': [3, 4, 9, 5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [37]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [38]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4

In [39]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [40]:
portfolio_df = pd.DataFrame({'Ticker Symbol':["AAPL", "AMZN", "GOOG"],
                 'Number of Shares': [3, 6, 3],
                 'Price [$]': [3500, 200, 3760]})
A = portfolio_df['Number of Shares']
B = portfolio_df['Price [$]']
stocks_dollar_value = A * B
stocks_dollar_value.sum()

22980

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [41]:
# Pandas is used to read a csv file and store data in a DataFrame


In [42]:
# Read tabular data using read_html
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1045)>

In [44]:
!pip install lxml

In [45]:
!python -m pip install --upgrade pip

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [47]:
table = pd.read_html(' https://www.ssa.gov/oact/progdata/nra.html')
table[0]

ImportError: html5lib not found, please install it

# TASK #8: PANDAS OPERATIONS

In [48]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444],
                               'Bank Client Name': ['Chanel', 'Steve', 'Mitch', 'Ryan'],
                                'Net Worth [$]': [3500, 29000, 10000, 2000],
                                 'Years with bank': [3, 4, 9, 5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [55]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_client_df[ bank_client_df['Years with bank'] >= 5 ]
df_loyal

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [56]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client ID']
bank_client_df

Bank Client Name  Net Worth [$]  Years with bank
0           Chanel           3500                3
1            Steve          29000                4
2            Mitch          10000                9
3             Ryan           2000                5

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [60]:
    high_networth = bank_client_df[ bank_client_df['Net Worth [$]'] >= 5000 ]
    high_networth['Net Worth [$]'].sum()

39000

# TASK #9: PANDAS WITH FUNCTIONS

In [5]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [6]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance * 1.2

In [8]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [9]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [12]:
portfolio_df = pd.DataFrame({'Ticker Symbol':["AAPL", "AMZN", "GOOG"],
                 'Number of Shares': [3, 6, 3],
                 'Price [$]': [3500, 200, 3760]})
#define the function
def triple_price(price):
    return price * 3 + 200
#apply the function
new_price = portfolio_df['Price [$]'].apply(triple_price)
new_price.sum()

22980

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [13]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [14]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [15]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [17]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by = 'Years with bank', inplace= True)

In [18]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [19]:
df1 = pd.DataFrame({ 'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3'],
                     'C': ['C0', 'C1', 'C2', 'C3'],
                     'D': ['D0', 'D1', 'D2', 'D3']},
                  index = [0, 1, 2, 3])

In [20]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [22]:
df2 = pd.DataFrame({ 'A': ['A4', 'A5', 'A6', 'A7'],
                     'B': ['B4', 'B5', 'B6', 'B7'],
                     'C': ['C4', 'C5', 'C6', 'C7'],
                     'D': ['D4', 'D5', 'D6', 'D7']},
                  index = [4, 5, 6, 7])

In [23]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [24]:
df3 = pd.DataFrame({ 'A': ['A8', 'A9', 'A10', 'A11'],
                     'B': ['B8', 'B9', 'B10', 'B11'],
                     'C': ['C8', 'C9', 'C10', 'C11'],
                     'D': ['D8', 'D9', 'D10', 'D11']},
                  index = [8, 9, 10, 11])

In [25]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [26]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [34]:
Bank_df_1 = pd.DataFrame({'ID': [1, 2, 3, 4, 5],
                          'f_name': ['lily', 'sam', 'bruno', 'oliver', 'leticia'],
                          'l_name': ['rose', 'smith', 'mars', 'burg', 'svet']})

Bank_df_1

ID   f_name l_name
0   1     lily   rose
1   2      sam  smith
2   3    bruno   mars
3   4   oliver   burg
4   5  leticia   svet

In [35]:
Bank_df_2 = pd.DataFrame({'ID': [6, 7, 8, 9, 10],
                          'f_name': ['emily', 'taylor', 'elon', 'oprah', 'jennifer'],
                          'l_name': ['black', 'swift', 'musk', 'winnfery', 'lopez']})
Bank_df_2

ID    f_name    l_name
0   6     emily     black
1   7    taylor     swift
2   8      elon      musk
3   9     oprah  winnfery
4  10  jennifer     lopez

In [37]:
bank_df_salary = pd.DataFrame({'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        'Annual salary [$ per year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]})
bank_df_salary

ID  Annual salary [$ per year]
0   1                       25000
1   2                       35000
2   3                       45000
3   4                       48000
4   5                       49000
5   6                       32000
6   7                       33000
7   8                       34000
8   9                       23000
9  10                       22000

In [39]:
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all

ID    f_name    l_name
0   1      lily      rose
1   2       sam     smith
2   3     bruno      mars
3   4    oliver      burg
4   5   leticia      svet
0   6     emily     black
1   7    taylor     swift
2   8      elon      musk
3   9     oprah  winnfery
4  10  jennifer     lopez

In [43]:
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'ID')
bank_df_all

ID    f_name    l_name  Annual salary [$ per year]
0   1      lily      rose                       25000
1   2       sam     smith                       35000
2   3     bruno      mars                       45000
3   4    oliver      burg                       48000
4   5   leticia      svet                       49000
5   6     emily     black                       32000
6   7    taylor     swift                       33000
7   8      elon      musk                       34000
8   9     oprah  winnfery                       23000
9  10  jennifer     lopez                       22000

In [44]:
new_client = {'ID': [11],
              'f_name': ['nadia'],
              'l_name': ['OUERDIANE'],
              'Annual salary [$ per year]': [500000]}
    
new_client_df = pd.DataFrame(new_client, columns = ['ID', 'f_name', 'l_name', 'Annual salary [$ per year]'])
new_client_df
    
    


ID f_name     l_name  Annual salary [$ per year]
0  11  nadia  OUERDIANE                      500000

In [45]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

ID    f_name     l_name  Annual salary [$ per year]
0   1      lily       rose                       25000
1   2       sam      smith                       35000
2   3     bruno       mars                       45000
3   4    oliver       burg                       48000
4   5   leticia       svet                       49000
5   6     emily      black                       32000
6   7    taylor      swift                       33000
7   8      elon       musk                       34000
8   9     oprah   winnfery                       23000
9  10  jennifer      lopez                       22000
0  11     nadia  OUERDIANE                      500000

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [ ]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [ ]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

In [ ]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
def networth_update(balance):
    return balance * 3 + 200 

In [ ]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

In [ ]:
results.sum()

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


In [ ]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

In [ ]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df